operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
hooks:
  pre-app-run: node node_modules/@adobe/uix-guest/scripts/generate-metadata.js
  pre-app-build: node node_modules/@adobe/uix-guest/scripts/generate-metadata.js
  post-app-deploy: ./hooks/post-deploy.js
runtimeManifest:
  packages:
    aem-cf-console-admin-1:
      license: Apache-2.0
      actions:
        export:
          function: actions/export/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            API_ENDPOINT: $API_ENDPOINT
          annotations:
            require-adobe-auth: false
            final: true
        delete:
          function: actions/delete/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            API_ENDPOINT: $API_ENDPOINT
          annotations:
            require-adobe-auth: false
            final: true
        publish:
          function: actions/publish/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            API_ENDPOINT: $API_ENDPOINT
          annotations:
            require-adobe-auth: false
            final: true