operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
hooks:
  pre-app-run: node node_modules/@adobe/uix-guest/scripts/generate-metadata.js
  pre-app-build: node node_modules/@adobe/uix-guest/scripts/generate-metadata.js
  post-app-deploy: ./hooks/post-deploy.js
runtimeManifest:
  packages:
    universal-editor-richtext-draft:
      license: Apache-2.0
      actions:
        save-draft:
          function: actions/save-draft/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            UNIVERSAL_EDITOR_URL: $UNIVERSAL_EDITOR_URL
          annotations:
            require-adobe-auth: true
            final: true
